rewrote zombie files
konecnyjakub/Danse_Macabre pull request #11
Opened 2017-02-27 06:17 UTC by sevu

don't bother comparing all that - writing code is easier than reading it.
only ingame change: wose/dwarf need 4 moves on deep water too
and drake die animation is a bit different

Death images with a number higher than 2 are now used from mainline, with the drake being an exception.
Only merrin & neckfrill still rely on them.

Oh, and while doing that I found a bug with the mainline zombies, good thing.

2017-02-27 10:38 UTC, konecnyjakub requested changes
You accidentally changed textdomain at first line of all 3 files. We need the original one for unit type's name and description.

2017-02-27 12:28 UTC, sevu commented
Haha, I looked so long to have no bugs, yet it is the most obvious thing.

2017-02-27 12:39 UTC, konecnyjakub commented
Why are the wolf and goblin variations commented out? If you want to get rid of the goblin variation, just remove the code. For wolf, are you just not finished with it yet? It might be good to add the wolf just for Wesnoth 1.13, on 1.12 it would end up unused anyway.

2017-02-27 13:14 UTC, konecnyjakub approved these changes

2017-02-28 02:13 UTC, sevu commented
We neither have pictures for the goblin, nor do we have for the wolf.
If we would, that's how they would look like, and the place in the code where it would be best.

2017-02-28 02:14 UTC, sevu commented
Btw, in 1.13 there are new soulless drake images.

2017-02-28 09:46 UTC, konecnyjakub commented
Well, the goblin variation is not strictly necessary as there is no way you could get a goblin zombie iirc (without using debug mode, that is). Anyway, I think that we can use soulless sprites for goblin and wolf until we get proper graphics (they would basically be just re-colored soulless actually).

2017-02-28 10:00 UTC, konecnyjakub commented on units/a2_Running_Corpse.cfg
> +    advances_to=Battalion
Running Corpse should advance into Brain Eater, not Battalion.

2017-02-28 10:14 UTC, konecnyjakub requested changes
Basic unit types' types, dwarf, mounted, saurian, swimmer, troll and wose sprites (and probably also their animations, I did not check them all) no longer work in game.

2017-02-28 10:24 UTC, konecnyjakub commented
Forgot to add the issue with sprites happens on both Wesnoth 1.12 and 1.13.

2017-03-01 00:25 UTC, sevu commented on units/a2_Running_Corpse.cfg
> +    {UNIT_BODY_RUNNING_CORPSE_DEATH BASE_NAME}
forgot the {brackets} around base_name

2017-03-01 00:31 UTC, sevu commented
Units which have no variation advance to the "normal" version, that would be the human soulless.
And true, it's currently not possible to get goblins.

2017-03-01 00:31 UTC, sevu commented on units/a2_Running_Corpse.cfg
> +    advances_to=Battalion
it really should o.O

2017-03-01 08:34 UTC, konecnyjakub approved these changes

2017-03-01 09:14 UTC, merged

2017-03-01 09:16 UTC, konecnyjakub commented
Works fine now.